DROP PROCEDURE TRANSCODE_G723;
DROP EXTERNAL FUNCTION UDF_TRANSCODE_G723;
COMMIT;

DECLARE EXTERNAL FUNCTION UDF_TRANSCODE_G723
    BLOB,
    BLOB
    RETURNS PARAMETER 2
    ENTRY_POINT 'transcode_g723'
    MODULE_NAME 'sosna_udf';
COMMIT;

SET TERM ^ ;

CREATE PROCEDURE TRANSCODE_G723 (
    rec_in BLOB SUB_TYPE 0
)
RETURNS (
    rec_out BLOB SUB_TYPE 0
)
AS
BEGIN
    IF (rec_in IS NOT NULL) THEN
    BEGIN
        rec_out = UDF_TRANSCODE_G723(rec_in);
    END
    ELSE
    BEGIN
        rec_out = NULL;
    END
    SUSPEND;
END^

SET TERM ; ^
COMMIT;
